### ISSUE TITLE
no connection to server

### ISSUE THREAD

**Issue by m8788** [ArthurGarnier/turtl-docker#14]
Hi, 

tried to connect from my ubuntu 18.04 host to your docker container, but it isn't working. It is my first time using docker, hope its not something stupid. Tried following links in the desktop turtl application or in the browser to see same as on https://api.turl.it/v2/ or on https://api.framanotes.org/ but nothing shows up except of "couldn't connect to server".
http://0.0.0.0:8181/
http://0.0.0.0/
http://turtl.local:8181/
http://turtl.local/
http://172.17.0.2:8181/
http://172.17.0.2/

$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
9041ea8902ab        turtl_docker        "/bin/sh -c /opt/tur…"   About an hour ago   Up About an hour    0.0.0.0:8181->8181/tcp   hardcore_mclean

$ nmap -Pn 0.0.0.0
Starting Nmap 7.60 ( https://nmap.org ) at 2018-08-17 21:05 CEST
PORT     STATE SERVICE     REASON  VERSION
139/tcp  open  netbios-ssn syn-ack Samba smbd 3.X - 4.X (workgroup: WORKGROUP)
445/tcp  open  netbios-ssn syn-ack Samba smbd 3.X - 4.X (workgroup: WORKGROUP)
631/tcp  open  ipp         syn-ack CUPS 2.2
8181/tcp open  tcpwrapped  syn-ack

$ sudo docker exec -i -t 9041ea8902ab /bin/bash
root@754d59014d74:/opt/api# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:ac:11:00:02  
          inet addr:172.17.0.2  Bcast:172.17.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:18279 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9460 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:27177605 (27.1 MB)  TX bytes:631788 (631.7 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

root@754d59014d74:/opt/api# nano /opt/turtl-setup
#!/bin/bash
default values
PIDFILE=${PIDFILE:-nil}
BINDADDR=${BINDADDR:-0.0.0.0}
BINDPORT=${BINDPORT:-8181}
PROD_ERR_HANDLING=${PROD_ERR_HANDLING:-t}
FQDN=${FQDN:-turtl.local}
SITE_URL=${SITE_URL:-http://turtl.local}
ADMIN_EMAIL=${ADMIN_EMAIL:-root@example.com}
EMAIL_FROM=${EMAIL_FROM:-noreply@example.com}
SMTP_USER=${SMTP_USER:-}
SMTP_PASS=${SMTP_PASS:-}
DISPLAY_ERRORS=${DISPLAY_ERRORS:-t}
DEFAULT_STORAGE_LIMIT=${DEFAULT_STORAGE_LIMIT:-100}
STORAGE_INVITE_CREDIT=${STORAGE_INVITE_CREDIT:-25}
LOCAL_UPLOAD_URL=${LOCAL_UPLOAD_URL:-http://turtl.local}
LOCAL_UPLOAD_PATH=${LOCAL_UPLOAD_PATH:-"/opt/api/uploads"}
AWS_S3_TOKEN=${AWS_S3_TOKEN:-(:token ''

Thought it is a basic connect from host to "server within docker" question, but haven't found anything helpful online.
 
Thank you very much!

**Comment by landowark** [comment]
I'm having the same issue. If I enter into the container, install net-tools and run:

root@afe4185371e1:/opt/api# netstat -a -n -o
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       Timer
tcp        0      0 127.0.0.1:28015         0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 127.0.0.1:29015         0.0.0.0:*               LISTEN      off (0.00/0/0)

To me, this means that the container is listening on port 8080, not port 8181 as appears in the documentation. I've tried connecting the hostport with 8080 in the container, but this doesn't produce any different results.

**Comment by massmux** [comment]
unfortunately this container does not work. in the logs i see

; Loading "turtl"
To load "secure-random":
  Load 1 ASDF system:
    cl+ssl
  Install 1 Quicklisp release:
    secure-random
; Fetching #<URL "http://beta.quicklisp.org/archive/secure-random/2016-02-08/secure-random-20160208-git.tgz">
; 2.84KB
==================================================
2,912 bytes in 0.00 seconds (2670.19KB/sec)
; Loading "secure-random"
[package secure-random]
; Loading "turtl"
To load "trivial-backtrace":
  Install 1 Quicklisp release:
    trivial-backtrace
; Fetching #<URL "http://beta.quicklisp.org/archive/trivial-backtrace/2016-05-31/trivial-backtrace-20160531-git.tgz">
; 8.73KB
==================================================
8,941 bytes in 0.00 seconds (8167.86KB/sec)
; Loading "trivial-backtrace"
[package trivial-backtrace]..
; Loading "turtl"
To load "xmls":
  Load 1 ASDF system:
    asdf
  Install 1 Quicklisp release:
    xmls
; Fetching #<URL "http://beta.quicklisp.org/archive/xmls/2018-04-30/xmls-3.0.2.tgz">
; 110.39KB
==================================================
113,037 bytes in 0.00 seconds (52615.68KB/sec)
; Loading "xmls"
[package xmls]...............
; Loading "turtl"
> Error: Unable to load any of the alternatives:
>           ("libcrypto.so.1.1" "libcrypto.so.1.0.2")
> While executing: CFFI::FL-ERROR, in process listener(1).
[package cl-async-ssl]
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip loading "launch.lisp"
> Type :? for other options.
1 > rethinkdb: instance1: Starting instance. (logging to `/var/lib/rethinkdb/instance1/data/log_file')
To load "turtl":
  Load 1 ASDF system:
    turtl
; Loading "turtl"
..................................................
> Error: Unable to load any of the alternatives:
>           ("libcrypto.so.1.1" "libcrypto.so.1.0.2")
> While executing: CFFI::FL-ERROR, in process listener(1).
[package cl-async-ssl]
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip loading "launch.lisp"
> Type :? for other options.
1 > rethinkdb: instance1: Starting instance. (logging to `/var/lib/rethinkdb/instance1/data/log_file')
To load "turtl":
  Load 1 ASDF system:
    turtl
; Loading "turtl"
..................................................
[package cl-async-ssl]
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip loading "launch.lisp"
> Type :? for other options.
> Error: Unable to load any of the alternatives:
>           ("libcrypto.so.1.1" "libcrypto.so.1.0.2")
> While executing: CFFI::FL-ERROR, in process listener(1).
1 > rethinkdb: instance1: Starting instance. (logging to `/var/lib/rethinkdb/instance1/data/log_file')
To load "turtl":
  Load 1 ASDF system:
    turtl
; Loading "turtl"
..................................................
[package cl-async-ssl]
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip loading "launch.lisp"
> Type :? for other options.
> Error: Unable to load any of the alternatives:
>           ("libcrypto.so.1.1" "libcrypto.so.1.0.2")
> While executing: CFFI::FL-ERROR, in process listener(1).
1 > rethinkdb: instance1: Starting instance. (logging to `/var/lib/rethinkdb/instance1/data/log_file')
To load "turtl":
  Load 1 ASDF system:
    turtl
; Loading "turtl"
..................................................
> Error: Unable to load any of the alternatives:
>           ("libcrypto.so.1.1" "libcrypto.so.1.0.2")
> While executing: CFFI::FL-ERROR, in process listener(1).
[package cl-async-ssl]
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip loading "launch.lisp"
> Type :? for other options.
1 > rethinkdb: instance1: Starting instance. (logging to `/var/lib/rethinkdb/instance1/data/log_file')
To load "turtl":
  Load 1 ASDF system:
    turtl
; Loading "turtl"
..................................................
> Error: Unable to load any of the alternatives:
>           ("libcrypto.so.1.1" "libcrypto.so.1.0.2")
> While executing: CFFI::FL-ERROR, in process listener(1).
[package cl-async-ssl]
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip loading "launch.lisp"
> Type :? for other options.
1 > rethinkdb: instance1: Starting instance. (logging to `/var/lib/rethinkdb/instance1/data/log_file')
To load "turtl":
  Load 1 ASDF system:
    turtl
; Loading "turtl"
..................................................
> Error: Unable to load any of the alternatives:
>           ("libcrypto.so.1.1" "libcrypto.so.1.0.2")
> While executing: CFFI::FL-ERROR, in process listener(1).
[package cl-async-ssl]
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip loading "launch.lisp"
> Type :? for other options.
1 > rethinkdb: instance1: Starting instance. (logging to `/var/lib/rethinkdb/instance1/data/log_file')
To load "turtl":
  Load 1 ASDF system:
    turtl
; Loading "turtl"
..................................................
> Error: Unable to load any of the alternatives:
>           ("libcrypto.so.1.1" "libcrypto.so.1.0.2")
> While executing: CFFI::FL-ERROR, in process listener(1).
[package cl-async-ssl]
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip loading "launch.lisp"
> Type :? for other options.
1 > rethinkdb: instance1: Starting instance. (logging to `/var/lib/rethinkdb/instance1/data/log_file')
To load "turtl":
  Load 1 ASDF system:
    turtl
; Loading "turtl"
..................................................
[package cl-async-ssl]
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip loading "launch.lisp"
> Type :? for other options.
> Error: Unable to load any of the alternatives:
>           ("libcrypto.so.1.1" "libcrypto.so.1.0.2")
> While executing: CFFI::FL-ERROR, in process listener(1).
1 > rethinkdb: instance1: Starting instance. (logging to `/var/lib/rethinkdb/instance1/data/log_file')
To load "turtl":
  Load 1 ASDF system:
    turtl
; Loading "turtl"
..................................................
> Error: Unable to load any of the alternatives:
>           ("libcrypto.so.1.1" "libcrypto.so.1.0.2")
> While executing: CFFI::FL-ERROR, in process listener(1).
[package cl-async-ssl]
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip loading "launch.lisp"
> Type :? for other options.

**Comment by massmux** [comment]
hello everybody. i have fixed the errors found with a fork of this project.
the forked project is: https://github.com/massmux/turtl
now all works. i hope to have helped

**Comment by ArthurGarnier** [comment]
Hello massmux, not had any time to look at this. You can make a pullrequest (please rebase your commits) with you edits so I can merge the changes.

**Comment by ArthurGarnier** [comment]
Hello, I pushed the fix found by massmux. 
I built the container again without any cache, ran : 
`docker run -d -p 127.0.0.1:8181:8181 -v $(pwd):/var/lib/rethinkdb/instance1 -t b8d51a0f89a0`

And it works perfectly for me : 

```
 docker logs 80e8f6781f1
rethinkdb: instance1: The instance is not running (there is no pid file)
rethinkdb: instance1: Starting instance. (logging to `/var/lib/rethinkdb/instance1/data/log_file')
To load "turtl":
  Load 1 ASDF system:
    turtl
; Loading "turtl"
..................................................
[package cl-hash-util]............................
[package cl-rethinkdb-util].......................
[package cl-rethinkdb-reql].......................
[package cl-rethinkdb]............................
..................................................
[package turtl]...................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..........
..................................................
[package turtl-thread]
  <INFO> [1537306492] turtl - Applying DB schema...
  <INFO> [1537306492] turtl - Schema applied: (:TABLES-ADD NIL :INDEXES NIL)
<NOTICE> [1537306492] wookie - (start) Starting Wookie  0.0.0.0:8181
```

**Comment by ArthurGarnier** [comment]
Some other people succeded to build and run the container (default conf). 
So I close this issue.
