### ISSUE TITLE
Authentication Failing After Upgrade

### ISSUE THREAD

**Issue by Sephster** [ArthurGarnier/turtl-docker#15]
Hello. I upgraded my Turtl client to version 0.70 and updated my docker instance at the same time. I am no longer able to login to my server as I keep getting the following message:

> Login failed -- Error: Authentication failed.

In addition, if I try to create a new account I get the following message:

> There was a problem saving that account. /users timed out.

Looking at my logs, I have the following:

```
<DEBUG> [1542023788] turtl - turtl error: #<SOCKET-EOF #<TCP-SOCKET #x30200397AB1D>: 0: NIL #x3020039ABB8D>
  <INFO> [1542023936] wookie - "POST /auth" 401 24
 <ERROR> [1542023936] wookie - (hook) Error running hooks: PRE-ROUTE: (socket #<TCP-SOCKET #x3020039C418D>): Authentication failed.
  <INFO> [1542023947] wookie - "POST /auth" 401 24
 <ERROR> [1542023947] wookie - (hook) Error running hooks: PRE-ROUTE: (socket #<TCP-SOCKET #x302003A397AD>): Authentication failed.
  <INFO> [1542023959] wookie - "POST /auth" 401 24
 <ERROR> [1542023959] wookie - (hook) Error running hooks: PRE-ROUTE: (socket #<TCP-SOCKET #x302003A4192D>): Authentication failed.
 <ERROR> [1542024002] turtl - check-auth: Query runtime error (NIL): Keys cannot be NULL.
---
#<REQL-CMD LIMIT/71 (#<REQL-CMD GET-ALL/78 (#<REQL-CMD TABLE/15 ("users")  #x302003ADB4CD> :NULL)  #x302003ADAB1D> 1)  #x302003ADA23D>
 <DEBUG> [1542024032] turtl - turtl error: #<SOCKET-EOF #<TCP-SOCKET #x302003A89E5D>: 0: NIL #x302003AFB18D>
```

Any ideas on what the issue could be here? Thanks for your help!

**Comment by moookino** [comment]
Same here for registration:

#<REQL-CMD LIMIT/71 (#<REQL-CMD GET-ALL/78 (#<REQL-CMD TABLE/15 ("users")  #x302003079A9D> :NULL)  #x3020030790ED> 1)  #x30200307880D>,
 <DEBUG> [1543591734] turtl - turtl error: #<SOCKET-EOF #<TCP-SOCKET #x302003019FCD>: 0: NIL #x302003098D0D>,

And authetntication failed:

 <ERROR> [1543591846] wookie - (hook) Error running hooks: PRE-ROUTE: (socket #<TCP-SOCKET #x3020031D867D>): Authentication failed.
  <INFO> [1543591846] wookie - "GET NIL" 500 66
 <DEBUG> [1543591846] turtl - turtl error: #<SOCKET-EOF #<TCP-SOCKET #x3020031D867D>: 0: NIL #x3020031F398D>

**Comment by ArthurGarnier** [comment]
I think this is an API issue not docker image one. 

- Does this happen on a fresh database? It seems a DB upgrade error

**Comment by moookino** [comment]
I've tried clean setup with all data removed and tried to open API url in browser

`rethinkdb:` instance1: The instance is not running (there is no pid file),
rethinkdb: instance1: Starting instance. (logging to `/var/lib/rethinkdb/instance1/data/log_file'),
Recursively removing directory /var/lib/rethinkdb/instance1/data/tmp,
To load "turtl":,
  Load 1 ASDF system:,,
l,
; Loading "turtl",
..................................................,
[package cl-hash-util]............................,
[package cl-rethinkdb-util].......................,
[package cl-rethinkdb-reql].......................,
[package cl-rethinkdb]............................,
..................................................,
[package turtl]...................................,
..................................................,
..................................................,
..................................................,
..................................................,
..................................................,
..................................................,
..................................................,
..................................................,
..................................................,
..................................................,
..........,
..................................................,
[package turtl-thread],
  <INFO> [1543826965] turtl - Applying DB schema...,
  <INFO> [1543826968] turtl - Schema applied: (:TABLES-ADD ("users" "boards" "notes" "personas" "boards_personas_link" "invites" "keychain" "sync" "log" "promo") :INDEXES (:PROMO (:ADD (:CODE)) :LOG (:ADD (:HASH)) :SYNC (:ADD (:REL :USER_SEARCH :SCAN_USER)) :KEYCHAIN (:ADD (:ITEM_ID :USER_ID)) :INVITES (:ADD (:FROM :TO :OBJ_TO)) :BOARDS_PERSONAS_LINK (:ADD (:FROM :TO :BOARD_ID)) :PERSONAS (:ADD (:USER_ID :EMAIL)) :NOTES (:ADD (:USER_ID :BOARDS :BOARD_ID)) :BOARDS (:ADD (:PARENT_ID :USER_ID :ID)) :USERS (:ADD (:INVITE_CODE :A)))),
<NOTICE> [1543826968] wookie - (start) Starting Wookie  0.0.0.0:8181,
  <INFO> [1543826974] wookie - "GET /" 401 24,
 <ERROR> [1543826974] wookie - (hook) Error running hooks: PRE-ROUTE: (socket #<TCP-SOCKET #x30200398440D>): Authentication failed.,
  <INFO> [1543826974] wookie - "GET NIL" 500 66,
 <DEBUG> [1543826974] turtl - turtl error: #<SOCKET-EOF #<TCP-SOCKET #x30200398440D>: 0: NIL #x3020039DD85D>,`

**Comment by moookino** [comment]
@ArthurGarnier  as API deprecated now, is it possibly root cause of this problem?
Should we use server instead of API?
Thanks in advance

**Comment by ArthurGarnier** [comment]
Just saw that, so yes it's probaly the cause. 
Should make a Dockerfile for the new server side, not sur to have the time these days.

**Comment by moookino** [comment]
@ArthurGarnier i've made setup my way, would you like me to post this solution here also?

**Comment by Sephster** [comment]
If you have a solution you could share, I would be interested in seeing it @moookino. Cheers

**Comment by ArthurGarnier** [comment]
If you have some hints to help me to provide a solution faster, it's welcome !

**Comment by moookino** [comment]
@Sephster @ArthurGarnier 
Hi, i've made a repo with steps, where you can find all relevant information, hope it solves your problems.
[https://github.com/moookino/docker-turtl-server](url)

Working for me on mobile and desktop clients

**Comment by Sephster** [comment]
Thanks @moookino. I will give this a go and let you know how I get on

**Comment by Sephster** [comment]
Thanks @moookino - I finally got around to upgrading my Turtl server. All went well. I tweaked mine slightly as I'm not using Traefik but all went according to plan. Thanks for pointing me in the right direction and thanks to @ArthurGarnier for originally setting up this Docker instance.
