### ISSUE TITLE
trurtl -run command instaling on ubuntu server-

### ISSUE THREAD

**Issue by eredwood007** [ArthurGarnier/turtl-docker#16]
I have a server running Ubuntu - 17.10. I am trying to install webofmars/turtl-docker. I was able to pull the install. But when I try to run with the command that I have [sudo docker build -t turtl_docker .]  I get a error: sudo docker build -t turtl_docker .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/eredwood/Dockerfile: no such file or directory
![selection_012](https://user-images.githubusercontent.com/6800926/49784081-b89df180-fce1-11e8-8da3-39e1f26e218a.png)
![turtldocker](https://user-images.githubusercontent.com/6800926/49785116-0e27cd80-fce5-11e8-80ae-ca38c2a1ffd6.png)

**Comment by ArthurGarnier** [comment]
Hello, 

I don't support the new API yet. 
But for the docker part, you are trying to build in the wrong directory, the Dockerfile is not in your home :)

**Comment by eredwood007** [comment]
This is very frustrating I understand what you are saying. But I am a new
user and I and new to this image. All I did was to pull and try to run this
but I getting this error message, and don't know what to do.  the direction
only show how to install it. This was to be the best Opposition.

Earnest L. Redwood
IT Consultant, Help-Desk-Support, Linux Consultant.
linuxmaster01@gmail.com
678 685-8422


*No programming language is perfect. There is not even a single best
language; there are only languages well suited or perhaps poorly suited for
particular purposes.*

*Herbert Mayer*

**Comment by ArthurGarnier** [comment]
Yes but there is 2 problems here  
1/ The API has migrated and is n longer based on Lisp. For the moment I don't support the new one
2/ Your problem is the way you use Docker

Can't help you now. I'll maybe take some time later to suppoer the new API.

**Comment by eredwood007** [comment]
Got it thanks and Happy holidays to you and yours.

Earnest L. Redwood
IT Consultant, Help-Desk-Support, Linux Consultant.
linuxmaster01@gmail.com
678 685-8422


*No programming language is perfect. There is not even a single best
language; there are only languages well suited or perhaps poorly suited for
particular purposes.*

*Herbert Mayer*
