### ISSUE TITLE
Failed to create endpoint <>

### ISSUE THREAD

**Issue by maxence-ai** [ArthurGarnier/turtl-docker#8]
When trying to run the freshly installed container, I get this response when executing `sudo docker run -d -p 8181:8181 -v $(pwd)/volume:/var/lib/rethinkdb/instance1 -t turtl_docker` : 

> 7579ea6e73f8824fff703d09059eff72d95a87fb8ebfba3d190d470824ab7863
> docker: Error response from daemon: failed to create endpoint furious_jones on network bridge: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -A DOCKER -p tcp -d 0/0 --dport 8181 -j DNAT --to-destination 172.17.0.2:8181 ! -i docker0' failed:.

Docker version : 1.10.3
Commit 6a0ed0c

**Comment by ArthurGarnier** [comment]
It seems to be a Docker issue, 
Maybe you're in a similar case : https://github.com/docker/docker/issues/18113#issuecomment-198194918

Try to restart your docker daemon and try again :)
